<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="use_2wd" value="1" />

    <xacro:if value="$(arg use_2wd)">
        <!-- Chassis -->
        <xacro:property name="chassis_width" value="0.6" />
        <xacro:property name="chassis_length" value="0.8" />
        <xacro:property name="chassis_height" value="0.2" />
        <xacro:property name="chassis_mass" value="0.4" />
        <xacro:property name="chassis_ground_clearance" value="0.05" />

        <!-- Wheels -->
        <xacro:property name="wheel_radius" value="${(chassis_height / 3.0) + chassis_ground_clearance}"/>
        <xacro:property name="wheel_width" value="0.05" />
        <xacro:property name="wheel_mass" value="0.1" />
        <xacro:property name="wheel_gap" value="0.01"/>

        <!-- Wheels -->
        <xacro:property name="castor_wheel_radius" value="${chassis_ground_clearance}"/>
        <xacro:property name="castor_mass" value="0.1"/>

        <!-- Diff Drive -->
         <xacro:property name="publish_odom_tf" value="true"/>

        <!-- Lidar -->
        <xacro:property name="lidar_width" value="0.0508"/>
        <xacro:property name="lidar_thickness" value="0.055"/>
        <xacro:property name="lidar_mass" value="0.125"/>
        <xacro:property name="visualize_lidar" value="false"/>
        <xacro:property name="lidar_min_range" value="0.12"/>
        <xacro:property name="lidar_max_range" value="30.0"/>

    </xacro:if>

</robot>