<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <!-- Include inertial macros -->
    <xacro:include filename="inertial.xacro" />

    <!-- Castor Wheel Macro -->
    <xacro:macro name="castor_wheel" params="name x_divide wheel_end_sign y_divide wheel_side_sign">

        <link name="${name}_link">
            <visual>
                <geometry>
                    <sphere radius="${castor_wheel_radius}" />
                </geometry>
                <material name="Grey"/>     
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${castor_wheel_radius}" />
                </geometry>
            </collision>

            <xacro:sphere_inertia mass="${castor_mass}" radius="${castor_wheel_radius}" />
        </link>

        <joint name="${name}_joint" type="fixed">
            <parent link="base_link" />
            <child link="${name}_link" />
            <origin xyz="${wheel_end_sign * (chassis_length / x_divide)} ${wheel_side_sign * (chassis_width / y_divide)} ${- (chassis_height / 2.0)}" rpy="0 0 0" />
        </joint>

        <gazebo reference="${name}_link">
            <material>Gazebo/Grey</material>
            <mu1>0.1</mu1>
            <mu2>0.1</mu2> 
            <kp>100000.0</kp> 
            <kd>10.0</kd> 
            <minDepth>0.001</minDepth> 
            <maxVel>0.1</maxVel>
        </gazebo>
        
    </xacro:macro>

</robot>