<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Include inertial macros -->
    <xacro:include filename="inertial.xacro" />


    <!-- Wheels Macro -->
    <xacro:macro name="wheel" params="name wheel_side_sign">

        <link name="${name}_link">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}" />
                </geometry>
                <material name="Orange"/>                                
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_radius}" />
                </geometry>
            </collision>
            <xacro:cyclinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_radius}" />
        </link>

        <joint name="${name}_joint" type="continuous">
            <parent link="base_link" />
            <child link="${name}_link" />
            <origin
                xyz="0.0 ${(wheel_side_sign * (chassis_width + wheel_width + wheel_gap)) / 2.0} ${wheel_radius - (chassis_ground_clearance + chassis_height / 2.0)}"
                rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>


        <gazebo reference="${name}_link">
            <material>Gazebo/Orange</material>
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <kp>100000.0</kp>
            <kd>10.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>0.1</maxVel>
        </gazebo>

    </xacro:macro>

</robot>
